project:
  type: website
  output-dir: docs

website:
  title: "Adipofat´s blog"
  navbar:
    right:
      - about.qmd
      - text: main
        href: https://arbones.github.io/adipo2/
      - icon: github
        href: https://github.com/arbones?tab=repositories
      - icon: youtube
        href: https://www.youtube.com/user/AdipoFat
  page-footer: 
    left: "© 2025 JM Arbones-Mainar"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

